name: AttemptsStatictic
main: com.req.attemptsstatictic.AttemptsStatistic
version: 1.0.0
api-version: '1.21'
authors: [ 'req' ]
commands:
  setattempts:
    description: Admin commands for attempts counter
    usage: /setattempts <reset|set <number>>
    permission: attemptsstatictic.admin
  attempts:
    description: Показать статистику попыток/смертей
    usage: /attempts
    permission: attemptsstatictic.mystats

permissions:
  attemptsstatictic.admin:
    default: op
  attemptsstatictic.mystats:
    default: true